#!/bin/bash

# Clean old files
rm -f nox-disk.img
rm -f nox-part.img

# 16M is all we want, we only want to 
# deal with FAT12 for now anyways
size=$((16 * 1024 * 1024))

dd if=/dev/zero of=nox-disk.img bs=$size count=1

# Initialize a new partition table, with a single
# partition starting at sector 2048, finishing at 32767,
# mark it as active, and set the type to FAT12
echo "o
n
p
1
2048
32767
a
1
t
1
w
" | fdisk nox-disk.img

# mkdosfs wants the file to exist already
touch nox-part.img 

# create the file system
mkdosfs -n "NOX" -F 12 nox-part.img $((8 * 1024))
