# Get the name of the module directory we're in
MODULE := $(dir $(lastword $(MAKEFILE_LIST)))

# Calculate directories to get sources from, and our object directory
CSOURCE_DIR := $(MODULE)source
ASOURCE_DIR := $(MODULE)source
OBJ_DIR := $(MODULE)obj
INCLUDE_DIR := $(MODULE)include
DEP_DIR := $(MODULE)deps

# Find all candidates for compiling
ASOURCE := $(shell find $(ASOURCE_DIR) -name '*.asm')
CSOURCE := $(shell find $(CSOURCE_DIR) -name '*.c')

# Remove kloader from standard Nox
ASOURCE := $(filter-out $(ASOURCE_DIR)/kloader_start.asm, $(ASOURCE))
CSOURCE := $(filter-out $(CSOURCE_DIR)/kloader_main.c, $(CSOURCE))

# Construct a list of all object files
COBJECTS := $(CSOURCE:.c=.o)
COBJECTS := $(subst $(CSOURCE_DIR), $(OBJ_DIR), $(COBJECTS))
AOBJECTS := $(ASOURCE:.asm=.o)
AOBJECTS := $(subst $(ASOURCE_DIR), $(OBJ_DIR), $(AOBJECTS))

#
# Compiler options
#
PLATFORM_DEBUG:=PLATFORM_DEBUG_BOCHS
PLATFORM_ARCH:=PLATFORM_ARCH_X86
PLATFORM_BITS_VAL:=32
CFLAGS=-std=c11 \
       -ffreestanding \
       -nostdlib \
       -Wall \
       -Werror \
       -c \
       -D $(PLATFORM_DEBUG) \
       -D $(PLATFORM_ARCH) \
       -D PLATFORM_BITS=$(PLATFORM_BITS_VAL)
CINCLUDE := $(patsubst %,-I%, $(shell find $(INCLUDE_DIR) -type d))

# Add prerequisites for full build
IMAGE_ASSETS += $(BUILD)/KERNEL.BIN $(BUILD)/BOOT.SYS

# Tell the main makefile to remove our object dir on clean
CLEAN_DIRS += $(OBJ_DIR) $(DEP_DIR)

#
# Include dependencies files automatically generated by previous builds
#
-include $(addprefix $(DEP_DIR)/, $(notdir $(COBJECTS:.o=.d)))

#
# Actually building stuff
#

# Note: Upper case because we use FAT12 and this makes it easy for now
$(BUILD)/KERNEL.BIN: $(OBJ_DIR)/kernel.elf 
	@echo "OBJCOPY $<"

	@$(TOOL)-objcopy $^ -O binary --set-section-flags .bss=alloc,load,contents $@

# Note: Build into root build directory
$(OBJ_DIR)/kernel.elf: kernel_directories $(COBJECTS) $(AOBJECTS)

	@echo "LD      $@"

	@$(TOOL)-ld -T kernel.ld -Map=$(BUILD)/kernel.map $(filter-out kernel_directories, $^) -o $@

$(OBJ_DIR)/%.o : $(CSOURCE_DIR)/%.c

	@mkdir -p $(dir $@)
	@mkdir -p $(DEP_DIR)/$(dir $*)
	@echo "CC      $<"

	@$(TOOL)-gcc $< -o $@ $(CINCLUDE) $(CFLAGS) -MD -MF $(DEP_DIR)/$*.d

$(OBJ_DIR)/%.o : $(ASOURCE_DIR)/%.asm

	@mkdir -p $(dir $@)

	@echo "AS      $<"

	@nasm $< -o $@ -f elf32 -i $(INCLUDE_DIR)

#################################################################################
#
# Kloader
#
################################################################################
KLOADER_CSOURCES := $(CSOURCE_DIR)/ata.c $(CSOURCE_DIR)/fat.c $(CSOURCE_DIR)/fs.c $(CSOURCE_DIR)/kloader_main.c $(CSOURCE_DIR)/mem_mgr.c $(CSOURCE_DIR)/pio.c $(CSOURCE_DIR)/screen.c $(CSOURCE_DIR)/terminal.c $(CSOURCE_DIR)/string.c $(CSOURCE_DIR)/kloader_main.c $(CSOURCE_DIR)/elf.c
KLOADER_ASOURCES := $(CSOURCE_DIR)/kloader_start.asm

KLOADER_OBJECTS := $(KLOADER_CSOURCES:.c=.o)
KLOADER_OBJECTS += $(KLOADER_ASOURCES:.asm=.o)
KLOADER_OBJECTS := $(subst $(CSOURCE_DIR), $(OBJ_DIR), $(KLOADER_OBJECTS))
KLOADER_OBJECTS := $(subst $(ASOURCE_DIR), $(OBJ_DIR), $(KLOADER_OBJECTS))

$(BUILD)/BOOT.SYS: $(BUILD)/boot.elf
	@echo "OBJCOPY $<"
	@@$(TOOL)-objcopy $^ -O binary --set-section-flags .bss=alloc,load,contents $@

$(BUILD)/boot.elf: kernel_directories $(KLOADER_OBJECTS)
	@echo "LD      $@" 
	@$(TOOL)-ld -T kloader.ld $(filter-out kernel_directories, $^) -o $@

kernel_directories:
	@mkdir -p $(DEP_DIR)
	@mkdir -p $(OBJ_DIR)

.PHONY: kernel_directories
