[package]
target = "x86-nox.json"
name = "noxrust"
version = "0.1.0"
authors = ["Simon Gustavsson <simon67041@gmail.com>"]
edition = "2018"
[lib]
crate-type = ["staticlib"]
target = "x86-nox.json"

[build]
target = "x86-nox.json"

